stages:
  simulate:
    cmd: python src/simulate.py
    deps:
    - src/simulate.py
    params:
    - seed
    - simulate
    outs:
    - ${simulate.out_file}

  prepare:
    cmd: python src/prepare.py ${simulate.out_file} ${prepare.train_out} ${prepare.test_out}
    deps:
    - ${simulate.out_file}
    - src/prepare.py
    params:
    - prepare
    - seed
    outs:
    - ${prepare.train_out}
    - ${prepare.test_out}

  train:
    cmd: >-
      python src/train.py ${prepare.train_out} ${train.model_out}
      --predicted-probabilities-plot ${train.predicted_probabilities_plot}
      --feature-importance-plot ${train.feature_importance_plot}
    deps:
    - ${prepare.train_out}
    - src/train.py
    params:
    - seed
    - train
    outs:
    - ${train.model_out}
    - ${train.predicted_probabilities_plot}:
        cache: true
    - ${train.feature_importance_plot}:
        cache: true

  evaluate:
    cmd: python src/evaluate.py ${prepare.test_out} ${train.model_out} ${evaluate.metrics_out} ${evaluate.confusion_matrix_plot} ${evaluate.roc_curve_plot}
    deps:
    - ${prepare.test_out}
    - ${train.model_out}
    - src/evaluate.py
    params:
    - evaluate
    outs:
    - ${evaluate.confusion_matrix_plot}:
        cache: true
    - ${evaluate.roc_curve_plot}:
        cache: true
    metrics:
    - ${evaluate.metrics_out}:
        cache: false

plots:
- plots
