stages:
  simulate:
    cmd: python src/simulate.py
    deps:
    - src/simulate.py
    params:
    - seed
    - simulate
    outs:
    - data/raw/measurements.csv

  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/measurements.csv
    - src/prepare.py
    params:
    - prepare
    - seed
    outs:
    - data/processed/test.csv
    - data/processed/train.csv

  train:
    cmd: python src/train.py
    deps:
    - data/processed/train.csv
    - src/train.py
    params:
    - seed
    - train
    outs:
    - models/model.joblib

  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/test.csv
    - models/model.joblib
    - src/evaluate.py
    # --- Add these plot outputs ---
    outs:                           # Use 'outs' instead of 'metrics' for plots
    - plots/confusion_matrix.png:
        cache: true
    - plots/roc_curve.png:
        cache: true
    # --- Keep the metrics definition ---
    metrics:
    - metrics/metrics.json:
        cache: false

plots:
- plots
